# Generated by Django 4.1.6 on 2024-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_scheduledmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='user',
        ),
    ]
