# Generated by Django 4.1.6 on 2024-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_diaryentry_updated_at_remove_diaryentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_name', models.CharField(max_length=100)),
                ('selected_image_url', models.URLField()),
            ],
        ),
    ]
