# Generated by Django 4.1.6 on 2024-07-08 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diary',
            name='selected_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
