# Generated by Django 4.1.6 on 2024-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_diaryentry_updated_at_diaryentry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='user',
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
