# Generated by Django 4.1.6 on 2024-07-08 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_diaryentry_user_alter_diaryentry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_name',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='selected_image_url',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='diary',
            name='cover',
            field=models.ImageField(default='diary_covers/default.jpg', upload_to='diary_covers/'),
        ),
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=('auth.Group',)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='diary',
            field=models.ForeignKey(default='diary_covers/default.jpg', on_delete=django.db.models.deletion.CASCADE, to='main.diary'),
            preserve_default=False,
        ),
    ]
