# Generated by Django 4.1.6 on 2024-07-09 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_diary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
