# Generated by Django 4.1.6 on 2024-07-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_diary_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='created_at',
        ),
    ]
